services:
  mysql:
    image: mysql:8.0
    container_name: mfa-mysql
    environment:
      MYSQL_DATABASE: mfa_db
      MYSQL_USER: mfa_user
      MYSQL_PASSWORD: mfa_pass
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: Europe/Warsaw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: mfa-backend
    environment:
      TZ: Europe/Warsaw
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mfa_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Warsaw
      SPRING_DATASOURCE_USERNAME: mfa_user
      SPRING_DATASOURCE_PASSWORD: mfa_pass
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: